name: Simple CI

on:
  push:

jobs:
  run-echo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: pip install faker

      - name: Run Python file
        run: python app.py  

